[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"

[dependencies]
lazy_static = "0.1"
rand = "0.8"
termcolor = "1.1"

[dependencies.mongodb]
mongodb = "2.1.0"
default-features = false
features = ["sync"]